#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2026 Vysakh P Pillai
# SPDX-License-Identifier: Apache-2.0

"""
Convert raw VGA frame data to animated GIF

Reads vga_frames.bin (generated by vga_capture.py) and creates an animated GIF.
"""

import struct
import sys
from pathlib import Path

try:
    from PIL import Image
    import numpy as np
except ImportError:
    print("Error: Required packages not installed.")
    print("Run: uv sync")
    sys.exit(1)


def main():
    input_file = Path("vga_frames.bin")
    output_file = Path("vga_output.gif")

    if not input_file.exists():
        print(f"Error: {input_file} not found.")
        print("Run the VGA capture simulation first:")
        print("  cd test && uv run apio raw -- make MODULE=vga_capture")
        sys.exit(1)

    print(f"Reading {input_file}...")

    with open(input_file, 'rb') as f:
        # Read header
        header = f.read(12)
        num_frames, width, height = struct.unpack('<III', header)
        print(f"Frames: {num_frames}, Resolution: {width}x{height}")

        frame_size = width * height * 3  # RGB bytes per frame
        frames = []

        for i in range(num_frames):
            frame_data = f.read(frame_size)
            if len(frame_data) != frame_size:
                print(f"Warning: Incomplete frame {i+1}")
                break

            # Convert to numpy array and reshape
            frame = np.frombuffer(frame_data, dtype=np.uint8).reshape((height, width, 3))
            frames.append(Image.fromarray(frame))
            print(f"  Frame {i+1}/{num_frames} loaded")

    print(f"Creating GIF: {output_file}...")

    # Save as animated GIF
    frames[0].save(
        output_file,
        save_all=True,
        append_images=frames[1:],
        duration=100,  # 100ms per frame (10 fps)
        loop=0  # Loop forever
    )

    print(f"Done! GIF saved to: {output_file}")
    print(f"File size: {output_file.stat().st_size / 1024:.1f} KB")


if __name__ == "__main__":
    main()
