#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2026 Vysakh P Pillai
# SPDX-License-Identifier: Apache-2.0

"""
Convert raw VGA frame data to animated GIF

Reads vga_frames.bin (generated by vga_capture.py) and creates animated GIFs:
- vga_output.gif: Frame-accurate capture (may play slow in browsers)
- vga_preview.gif: Browser-compensated version (real-time playback)
"""

import struct
import sys
from pathlib import Path

try:
    from PIL import Image
    import numpy as np
except ImportError:
    print("Error: Required packages not installed.")
    print("Run: uv sync")
    sys.exit(1)


def save_gif(frames, output_file, duration, description):
    """Save frames as animated GIF."""
    frames[0].save(
        output_file,
        save_all=True,
        append_images=frames[1:],
        duration=duration,
        loop=0,
        optimize=True
    )
    size_kb = output_file.stat().st_size / 1024
    print(f"  {output_file}: {len(frames)} frames @ {duration}ms ({description}) - {size_kb:.1f} KB")


def main():
    input_file = Path("vga_frames.bin")

    if not input_file.exists():
        print(f"Error: {input_file} not found.")
        print("Run the VGA capture simulation first:")
        print("  cd test && uv run apio raw -- make MODULE=vga_capture")
        sys.exit(1)

    print(f"Reading {input_file}...")

    with open(input_file, 'rb') as f:
        # Read header
        header = f.read(12)
        num_frames, width, height = struct.unpack('<III', header)
        print(f"Frames: {num_frames}, Resolution: {width}x{height}")

        frame_size = width * height * 3  # RGB bytes per frame
        frames = []

        for i in range(num_frames):
            frame_data = f.read(frame_size)
            if len(frame_data) != frame_size:
                print(f"Warning: Incomplete frame {i+1}")
                break

            # Convert to numpy array and reshape
            frame = np.frombuffer(frame_data, dtype=np.uint8).reshape((height, width, 3))
            frames.append(Image.fromarray(frame))

        print(f"  Loaded {len(frames)} frames")

    print("Creating GIFs...")

    # 1. Frame-accurate GIF (17ms per frame, browsers may enforce 20ms minimum)
    save_gif(frames, Path("vga_output.gif"), 17, "frame-accurate")

    # 2. Browser-compensated preview GIF
    # Browsers enforce ~20ms minimum delay, making 60fps content play at ~50fps.
    # To maintain real-time animation speed, we skip frames:
    # - Original: 60fps (16.67ms/frame)
    # - Browser: 50fps (20ms/frame)
    # - Skip ratio: 60/50 = 1.2 (keep every 1.2th frame, ~83% of frames)
    preview_indices = [int(i * 1.2) for i in range(len(frames) * 5 // 6)]
    preview_indices = [i for i in preview_indices if i < len(frames)]
    preview_frames = [frames[i] for i in preview_indices]
    save_gif(preview_frames, Path("vga_preview.gif"), 20, "browser-compensated")

    print("Done!")


if __name__ == "__main__":
    main()
